CREATE TABLE [Empresas]
(
  [COD_REGISTRO_ANS] VARCHAR(10) NOT NULL PRIMARY KEY,
  [COD_CNPJ] VARCHAR(25),
  [DES_RAZAO] VARCHAR(255),
  [DES_NOME_FANTASIA] VARCHAR(255),
  [DES_MODALIDADE] VARCHAR(100),
  [DES_LOGRADOURO] VARCHAR(100),
  [NUMERO] VARCHAR(20),
  [DES_COMPLEMENTO] VARCHAR(150),
  [DES_BAIRRO] VARCHAR(100),
  [DES_CIDADE] VARCHAR(100),
  [DES_UF] VARCHAR(5),
  [COD_CEP] VARCHAR(12),
  [COD_DDD] VARCHAR(5),
  [NUM_TELEFONE] VARCHAR(20),
  [COD_FAX] VARCHAR(30),
  [DES_EMAIL] VARCHAR(255),
  [DES_REPRESENTANTE] VARCHAR(100),
  [DES_CARGO_REPRESENTANTE]  VARCHAR(100),
  [NUM_REGIAO] VARCHAR(3),
  [DTA_REGISTRO_ANS] VARCHAR(15)
)
