CREATE TABLE [Empresas]
(
  [COD_REGISTRO_ANS] INT NOT NULL PRIMARY KEY,
  [COD_CNPJ] VARCHAR(25) NOT NULL,
  [DES_RAZAO] VARCHAR(255) NOT NULL,
  [DES_NOME_FANTASIA] VARCHAR(255),
  [DES_MODALIDADE] VARCHAR(100) NOT NULL,
  [DES_LOGRADOURO] VARCHAR(100) NOT NULL,
  [NUMERO] VARCHAR(20),
  [DES_COMPLEMENTO] VARCHAR(150),
  [DES_BAIRRO] VARCHAR(100),
  [DES_CIDADE] VARCHAR(100),
  [DES_UF] VARCHAR(2) NOT NULL,
  [COD_CEP] VARCHAR(9) NOT NULL,
  [COD_DDD] VARCHAR(3),
  [NUM_TELEFONE] VARCHAR(20),
  [COD_FAX] VARCHAR(20),
  [DES_EMAIL] VARCHAR(255),
  [DES_REPRESENTANTE] VARCHAR(100),
  [DES_CARGO_REPRESENTANTE]  VARCHAR(100),
  [NUM_REGIAO] INT,
  [DTA_REGISTRO_ANS] DATETIME
)
 
CREATE TABLE [Demonstracoes_Contabeis]
(
  [DTA] DATETIME,
  [COD_REGISTRO_ANS] INT NOT NULL,
  [CD_CONTA_CONTABIL] VARCHAR(15),
  [DESCRICAO] VARCHAR(255),
  [VLR_SALDO_INICIAL] MONEY,
  [VLR_SALDO_FINAL] MONEY
)