# Generated by Django 5.1.7 on 2025-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cod_regiao',
            field=models.IntegerField(),
        ),
    ]
