# Generated by Django 5.1.7 on 2025-03-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empresa_cod_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cod_cep',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cod_regiao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_bairro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_cargo_representante',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_cidade',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_complemento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_logradouro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_modalidade',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_razao_social',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_representante',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='des_uf',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='dta_ans',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='num_ddd',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='num_fax',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='num_telefone',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='numero',
        ),
    ]
