# Generated by Django 5.1.7 on 2025-03-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_empresa_cod_cep_remove_empresa_cod_regiao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
